In [0]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)


In [0]:
downloaded = drive.CreateFile({'id':'11yYeZXGfgjHTiAVfC-F_jgxOq2ScUgXQ'}) 
downloaded.GetContentFile('Churn_Modelling.csv')  #https://drive.google.com/open?id=11yYeZXGfgjHTiAVfC-F_jgxOq2ScUgXQ

In [0]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [0]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
print(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
print(X[:,2])
onehotencoder = OneHotEncoder()
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(transformer.fit_transform(X), dtype=np.float)
#X = transformer.fit_transform(X).toarray()
#X = onehotencoder.fit_transform(X).toarray()
# Avoiding dummy variable trap by removing one dummy coloum in geography
X = X[:, 1:]
print(X)

[0. 0. 0. ... 0. 1. 0.]
[228. 217. 111. ... 318. 381. 401.]
[[0.0000000e+00 0.0000000e+00 2.2800000e+02 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 2.1700000e+02 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 1.1100000e+02 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [0.0000000e+00 0.0000000e+00 3.1800000e+02 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [1.0000000e+00 0.0000000e+00 3.8100000e+02 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [0.0000000e+00 0.0000000e+00 4.0100000e+02 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [0]:
print(X)
dataset

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
print(X_train)
print(X_test)

In [0]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  app.launch_new_instance()





Epoch 1/100





8000/8000 [==============================] - 2s 202us/step - loss: 0.4873 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4295 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.4249 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4199 - acc: 0.8075
Epoch 5/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4171 - acc: 0.8251
Epoch 6/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4148 - acc: 0.8274
Epoch 7/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4129 - acc: 0.8309
Epoch 8/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4114 - acc: 0.8325
Epoch 9/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4103 - acc: 0.8330
Epoch 10/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4092 - acc

In [0]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [0]:
cm

array([[1548,   47],
       [ 273,  132]])